### ISSUE TITLE
Rename to ovsdb-mon

### ISSUE THREAD

**Issue by amorenoz** [amorenoz/ovsdb-mon#17]
This project should also work with OvS or OVN SB, or any other OVNDB. How about we rename the project and binary to reflect that?

**Comment by amorenoz** [comment]
@flavio-fernandes wdyt? should we rename this to "ovsdb-mon"?

**Comment by flavio-fernandes** [comment]
> @flavio-fernandes wdyt? should we rename this to "ovsdb-mon"?

That sounds very reasonable, @amorenoz . 
There is nothing about this project that ties it to OVN. I think that makes it even more useful.

Have you considered other names as well? I actually like ovsdb-mon but while doing little more brainstorming on
it, I thought of:
- monovsdb
- mon-ovsdb
- ovsdb-walker
- ovsdb-crawler
- ovsdb-watcher
- ovsdb-view

-- flaviof

**Comment by amorenoz** [comment]
Thanks for your suggestions

> Have you considered other names as well? I actually like ovsdb-mon but while doing little more brainstorming on
> it, I thought of:
> 
>     * monovsdb
> 
>     * mon-ovsdb
> 

mono is monkey in Spanish, it's quite a distraction  for me :D

>     * ovsdb-walker
> 
>     * ovsdb-crawler
> 

I think this is too simple to call it a crawler since it's just capable of listing tables and monitor changes :-)

>     * ovsdb-watcher
> 

This one is nice, but I think I still prefer the word monitor better than watcher as it's the word that the ovsdb spec uses

>     * ovsdb-view
> 

ovsdb-view seems well fitted as well, I also like it

**Comment by flavio-fernandes** [comment]
> Thanks for your suggestions
> 
> > Have you considered other names as well? I actually like ovsdb-mon but while doing little more brainstorming on
> > it, I thought of:
> > ```
> > * monovsdb
> > 
> > * mon-ovsdb
> > ```
> 
> mono is monkey in Spanish, it's quite a distraction for me :D

LOL

> 
> > ```
> > * ovsdb-walker
> > 
> > * ovsdb-crawler
> > ```
> 
> I think this is too simple to call it a crawler since it's just capable of listing tables and monitor changes :-)
> 
> > ```
> > * ovsdb-watcher
> > ```
> 
> This one is nice, but I think I still prefer the word monitor better than watcher as it's the word that the ovsdb spec uses
> 
> > ```
> > * ovsdb-view
> > ```
> 
> ovsdb-view seems well fitted as well, I also like it

Cool beans. But 'ovsdb-mon' is nice too. Take your pick. :)
