### ISSUE TITLE
[RFE] Make tab complete case insensitive 

### ISSUE THREAD

**Issue by lewisdenny** [amorenoz/ovsdb-mon#24]
Hi Team, 

Using the tab complete function is fanatic but it's a small annoyance to have to use the correct case. 

If it is an easy change I think it would be worth it.

Example:
~~~
list logical_Flow <tab> <tab> Won't work. 
~~~

**Comment by amorenoz** [comment]
Looking at this @lewisdenny. The completion system is preformed by a library we use, it's not implemented in ovsdb-mon.
What we can do is add also the lower case versions of the tables and columns, so for instance:


```
>>> list  <tab> <tab>
Logical_Router logical_router Logical_Switch logical_switch ...
>>> list logi <tab> <tab>
logical_router logical_switch
>>> list logical_r <tab> <tab>
>>> list logical_router
```
(same for columns)

It would fix the problem of not starting a table name with a capital letter but:
- It would show both lower case and standard case options when you "tab" on an empty which is weird
- It would only help with "all lower" version of the tables, if we want to add all possible casing, they would all show all of them if more than one match, eg: if we accept "logical_switch" and "logicalSwitch" and "logical_Switch" and you type `logical <tab><tab>` you'd get all 3

**Comment by amorenoz** [comment]
Wait! I just found a way around
